name: Ionic CI/CD with Cypress
on:
  pull_request:
     types: [opened, synchronize, reopened]
  

jobs:
  test-e2e:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: ionic build
          start: ionic serve